clc;clear all;close all;
lamda=10;
beta=0.002;
d=0.01;
p=0.03;
a=0.24;
l=0.001;
s=0.2;
b=0.002;
Tm=1500;
T=700;
X0=50;
Y0=50;
Z0=2;
A=2;
A1=10;
A2=20;
[t f1]=simulation_HIV(lamda,beta,d,p,a,l,s,b,Tm,T,X0,Y0,Z0,A,A1,A2);
figure(1)
subplot(2,1,1);plot(t,f1(7,:),'black','Linewidth',2);
subplot(2,1,1);xlabel('Time = 600 days');
subplot(2,1,1);ylabel('The Optimal Control u(t)');
grid on;
%--------------------------------------------------------------------------
subplot(2,1,2);plot(t,f1(1,:),'blue','Linewidth',2);
hold on;
subplot(2,1,2);plot(t,f1(4,:),'--blue','Linewidth',2);
subplot(2,1,2);xlabel('Time = 600 days');
subplot(2,1,2);ylabel('Uninfected CD4+ T-Cell (X)');
legend('Before Treatment','After Treatment');
grid on;
%--------------------------------------------------------------------------
figure(2)
subplot(2,1,1);plot(t,f1(2,:),'green','Linewidth',2);
hold on;
subplot(2,1,1);plot(t,f1(5,:),'--green','Linewidth',2);
subplot(2,1,1);xlabel('Time = 600 days');
subplot(2,1,1);ylabel('Infected CD4+ T-Cell (Y)');
legend('Before Treatment','After Treatment');
grid on;
%--------------------------------------------------------------------------
subplot(2,1,2);plot(t,f1(3,:),'red','Linewidth',2);
hold on;
subplot(2,1,2);plot(t,f1(6,:),'--red','Linewidth',2);
subplot(2,1,2);xlabel('Time = 600 days');
subplot(2,1,2);ylabel('Immune Response (Z)');
legend('Before Treatment','After Treatment');
grid on;
figure(3);
%Combination between HAART and Immunotherapy Using IL-2
subplot(2,1,1);plot(t,f1(11,:),'black','Linewidth',2);
hold on;
subplot(2,1,1);plot(t,f1(7,:),'--blue','Linewidth',2);
subplot(2,1,1);xlabel('Time = 600 days');
subplot(2,1,1);ylabel('The Optimal Control u1(t)');
legend('HAART+Immunotherapy','HAART Only');
grid on;
hold on;
subplot(2,1,2);plot(t,f1(12,:),'red','Linewidth',2);
subplot(2,1,2);xlabel('Time = 600 days');
subplot(2,1,2);ylabel('The Optimal Control u2(t)');
grid on;
figure(4);
plot(t,f1(1,:),'blue','Linewidth',2);
hold on;
plot(t,f1(4,:),'red','Linewidth',2);
hold on;
plot(t,f1(8,:),'green','Linewidth',2);
hold on;
xlabel('Time = 600 days');
ylabel('Uninfected CD4+ T-Cell (X)');
legend('No Treatment','HAART Only','HAART+Immunotherapy');
grid on;
figure(5);
plot(t,f1(2,:),'blue','Linewidth',2);
hold on;
plot(t,f1(5,:),'red','Linewidth',2);
hold on;
plot(t,f1(9,:),'green','Linewidth',2);
hold on;
xlabel('Time = 600 days');
ylabel('Infected CD4+ T-Cell (Y)');
legend('No Treatment','HAART Only','HAART+Immunotherapy');
grid on;
figure(6);
plot(t,f1(3,:),'blue','Linewidth',2);
hold on;
plot(t,f1(6,:),'red','Linewidth',2);
hold on;
plot(t,f1(10,:),'green','Linewidth',2);
hold on;
xlabel('Time = 600 days');
ylabel('Immune Response(Z)');
legend('No Treatment','HAART Only','HAART+Immunotherapy');
grid on;